### ISSUE TITLE
Android dependencies on domain layer 

### ISSUE THREAD

**Issue by fahim-choudhury** [utpal-barman/Weather-Compose-Android#1]
If we want to strictly follow different layers for separation of concern, then the domain layer shouldn't have any Android dependencies. 

This class should be placed on the app/ui/presentation layer (whatever you call it).

https://github.com/utpal-barman/Weather-Compose-Android/blob/develop/app/src/main/java/io/github/utpal_barman/weatherandroid/domain/module/AppModule.kt

@utpal-barman

**Comment by utpal-barman** [comment]
Resolved in [this PR](https://github.com/utpal-barman/Weather-Compose-Android/pull/2)
